### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'unsqueeze'

### ISSUE THREAD

**Issue by freshwindy** [keonlee9420/Cross-Speaker-Emotion-Transfer#4]
I train have error :AttributeError: 'NoneType' object has no attribute 'unsqueeze'

**Comment by keonlee9420** [comment]
Hi @freshwindy , where did you get this error?

**Comment by lethanhson9901** [comment]
I got the same error when training, at evaluation step:
![Screenshot from 2022-05-25 17-04-52](https://user-images.githubusercontent.com/49090718/170237561-1ebaf847-b8bc-4b2b-a79c-af66467d51c8.png)

Traceback to this:
![Screenshot from 2022-05-25 17-06-00](https://user-images.githubusercontent.com/49090718/170237740-2e042fb3-8014-4dc1-b13c-5a54e25a3285.png)

**Comment by Lethanhson9901** [comment]
Please fix this bug :(

**Comment by lethanhson9901** [comment]
I think this error came from evaluation

**Comment by keonlee9420** [comment]
Hi all, sorry for the late response. I just updated the repo with fixes of all issues (v0.2.0). Please check it out! Thanks.
