### ISSUE TITLE
RuntimeError: Error(s) in loading state_dict for XSpkEmoTrans

### ISSUE THREAD

**Issue by 2333557** [keonlee9420/Cross-Speaker-Emotion-Transfer#5]
![image](https://user-images.githubusercontent.com/38718478/166678168-aca7d545-3644-4deb-9782-51272d308170.png)

**Comment by 2333557** [comment]
Device of XSpkEmoTrans: cuda
No module named 'lightconv_cuda'
No module named 'lightconv_cuda'
No module named 'lightconv_cuda'
No module named 'lightconv_cuda'
No module named 'lightconv_cuda'
No module named 'lightconv_cuda'
No module named 'lightconv_cuda'
22222222222222222222222222
Traceback (most recent call last):
  File "H:/talking_Head/unity_Project/Cross-Speaker-Emotion-Transfer-main/synthesize.py", line 206, in <module>
    ignore_layers=train_config["ignore_layers"])
  File "H:\talking_Head\unity_Project\Cross-Speaker-Emotion-Transfer-main\utils\model.py", line 29, in get_model
    model.load_state_dict(model_dict, strict=False)
  File "G:\Anaconda3\envs\ETTS\lib\site-packages\torch\nn\modules\module.py", line 1052, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for XSpkEmoTrans:
	size mismatch for duratin_predictor.lconv_stack.0.conv_layer.weight: copying a param with shape torch.Size([2, 3]) from checkpoint, the shape in current model is torch.Size([2, 1, 3]).
	size mismatch for decoder.lconv_stack.0.conv_layer.weight: copying a param with shape torch.Size([8, 15]) from checkpoint, the shape in current model is torch.Size([8, 1, 15]).
	size mismatch for decoder.lconv_stack.1.conv_layer.weight: copying a param with shape torch.Size([8, 15]) from checkpoint, the shape in current model is torch.Size([8, 1, 15]).
	size mismatch for decoder.lconv_stack.2.conv_layer.weight: copying a param with shape torch.Size([8, 15]) from checkpoint, the shape in current model is torch.Size([8, 1, 15]).
	size mismatch for decoder.lconv_stack.3.conv_layer.weight: copying a param with shape torch.Size([8, 15]) from checkpoint, the shape in current model is torch.Size([8, 1, 15]).
	size mismatch for decoder.lconv_stack.4.conv_layer.weight: copying a param with shape torch.Size([8, 15]) from checkpoint, the shape in current model is torch.Size([8, 1, 15]).
	size mismatch for decoder.lconv_stack.5.conv_layer.weight: copying a param with shape torch.Size([8, 15]) from checkpoint, the shape in current model is torch.Size([8, 1, 15]).

**Comment by freshwindy** [comment]
I also have the error:" No module named 'lightconv_cuda'",what is the reason for this error

**Comment by lethanhson9901** [comment]
I have the same error. I guess it's in class XSpkEmoTrans.py but don't know how to fix this.

**Comment by keonlee9420** [comment]
Hey guys, please refer to https://github.com/keonlee9420/Parallel-Tacotron2/issues/11 for the issue.

**Comment by keonlee9420** [comment]
Hi all, sorry for the late response. I just updated the repo with fixes of all issues (v0.2.0). Please check it out! Thanks.
