### ISSUE TITLE
loading state dict ——size mismatch

### ISSUE THREAD

**Issue by cythc** [keonlee9420/Cross-Speaker-Emotion-Transfer#7]
I have a problem when I use your pre-trained model for synthesis.
However, the following error happens:

**RuntimeError: Error(s) in loading state_dict for XSpkEmoTrans:
        size mismatch for duratin_predictor.lconv_stack.0.conv_layer.weight: copying a param with shape torch.Size([2, 3]) from checkpoint, the shape in current model is torch.Size([2, 1, 3]).
        size mismatch for decoder.lconv_stack.0.conv_layer.weight: copying a param with shape torch.Size([8, 15]) from checkpoint, the shape in current model is torch.Size([8, 1, 15]).
        size mismatch for decoder.lconv_stack.1.conv_layer.weight: copying a param with shape torch.Size([8, 15]) from checkpoint, the shape in current model is torch.Size([8, 1, 15]).
        size mismatch for decoder.lconv_stack.2.conv_layer.weight: copying a param with shape torch.Size([8, 15]) from checkpoint, the shape in current model is torch.Size([8, 1, 15]).
        size mismatch for decoder.lconv_stack.3.conv_layer.weight: copying a param with shape torch.Size([8, 15]) from checkpoint, the shape in current model is torch.Size([8, 1, 15]).
        size mismatch for decoder.lconv_stack.4.conv_layer.weight: copying a param with shape torch.Size([8, 15]) from checkpoint, the shape in current model is torch.Size([8, 1, 15]).
        size mismatch for decoder.lconv_stack.5.conv_layer.weight: copying a param with shape torch.Size([8, 15]) from checkpoint, the shape in current model is torch.Size([8, 1, 15]).**

**Comment by lethanhson9901** [comment]
https://github.com/keonlee9420/Cross-Speaker-Emotion-Transfer/issues/5#issuecomment-1122538073

**Comment by keonlee9420** [comment]
Hi all, sorry for the late response. I just updated the repo with fixes of all issues (v0.2.0). Please check it out! Thanks.
